[package]
name = "keypress"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.4.5"
serde = { version = "1.0.210", features = ["derive"]}
serde_json = "1.0.128"
willhook = { version ="0.6.3", features = ["serde"]}
